/**
 * Assert `src/lib/types.ts` still describes what the backend actually serializes (roadmap 11.3).
 *
 * Generates TypeScript from the backend's OpenAPI schema, emits one structural assertion per
 * mapped pair, and type-checks the result. The generated types are never imported by
 * application code: `types.ts` stays the hand-written source, because its JSDoc is real
 * documentation that codegen would destroy.
 */

import { execFileSync } from "node:child_process";
import { existsSync, writeFileSync } from "node:fs";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import openapiTS, { astToString } from "openapi-typescript";

import { SCHEMA_MAP, UNMAPPED } from "../src/lib/contract/map.mjs";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SCHEMA_PATH = path.resolve(ROOT, process.env.OPENAPI_JSON ?? "openapi.json");
const CONTRACT_DIR = path.join(ROOT, "src", "lib", "contract");
const GENERATED = path.join(CONTRACT_DIR, "generated.ts");
const ASSERTIONS = path.join(CONTRACT_DIR, "assert.ts");

const DUMP_COMMAND = "cd backend && python -m scripts.dump_openapi ../frontend/openapi.json";

function fail(message) {
  console.error(`\ncontract: ${message}\n`);
  process.exit(1);
}

/** Every backend schema must be mapped or deliberately unmapped, and every entry must still exist. */
function checkCoverage(schemas) {
  const backend = new Set(Object.keys(schemas));
  const known = new Set([...Object.keys(SCHEMA_MAP), ...Object.keys(UNMAPPED)]);

  const unrecognized = [...backend].filter((name) => !known.has(name)).sort();
  if (unrecognized.length > 0) {
    fail(
      `backend schema not accounted for in src/lib/contract/map.mjs: ${unrecognized.join(", ")}\n` +
        "Add it to SCHEMA_MAP with its frontend interface, or to UNMAPPED with a reason.",
    );
  }

  const stale = [...known].filter((name) => !backend.has(name)).sort();
  if (stale.length > 0) {
    fail(
      `map.mjs names a backend schema that no longer exists: ${stale.join(", ")}\n` +
        "Remove the entry.",
    );
  }
}

function renderAssertions() {
  const lines = Object.entries(SCHEMA_MAP)
    .sort(([, a], [, b]) => a.localeCompare(b))
    .map(
      ([backend, frontend]) =>
        `export const _${frontend}: Assert<Local.${frontend}, Gen["${backend}"]> = true;`,
    );

  return `// Generated by scripts/contract.mjs. Do not edit, do not commit, do not import.
import type * as Local from "../types";
import type { components } from "./generated";

type Gen = components["schemas"];

// Required<> only reaches the top level, and four responses nest models whose fields are
// optional on the generated side alone (FinancialsResponse, AnalysisListResponse,
// SimilarFilingsResponse, SectorCountsResponse). The recursion is what makes those four
// compare their elements rather than pass vacuously. The array branch must come first, or
// the object branch maps an array's own index signature.
type DeepRequired<T> = T extends (infer U)[]
  ? DeepRequired<U>[]
  : T extends object
    ? { [K in keyof T]-?: DeepRequired<T[K]> }
    : T;

type Exact<A, B> = [A] extends [B] ? ([B] extends [A] ? true : never) : never;

// Optionality is deliberately not compared; null-ness is. FastAPI marks a field optional when
// the Pydantic model gives it a default, which describes input defaulting rather than response
// serialization: \`filing_date: str | None = None\` is always present as null on the wire, so the
// frontend's required \`filing_date: string | null\` is the more accurate description. Comparing
// optionality would fail on ~15 fields that are not wrong. \`string | null\` vs \`string\` still
// fails, and so does \`string | null\` vs \`string | undefined\`.
type Assert<L, G> = Exact<DeepRequired<L>, DeepRequired<G>>;

${lines.join("\n")}
`;
}

if (!existsSync(SCHEMA_PATH)) {
  fail(
    `no OpenAPI schema at ${path.relative(ROOT, SCHEMA_PATH)}\nGenerate it with:\n  ${DUMP_COMMAND}`,
  );
}

const schema = JSON.parse(await readFile(SCHEMA_PATH, "utf8"));
const schemas = schema.components?.schemas;
if (!schemas) {
  fail(`${path.relative(ROOT, SCHEMA_PATH)} has no components.schemas`);
}

checkCoverage(schemas);

writeFileSync(GENERATED, astToString(await openapiTS(pathToFileURL(SCHEMA_PATH))), "utf8");
const assertions = renderAssertions();
writeFileSync(ASSERTIONS, assertions, "utf8");

const pairs = Object.keys(SCHEMA_MAP).length;
console.log(`contract: ${pairs} mapped pairs, ${Object.keys(UNMAPPED).length} unmapped`);

/** A tsc error points at a line of assert.ts; say which pair that line is. */
function nameFailures(output) {
  const source = assertions.split("\n");
  const seen = new Set();

  for (const line of output.split("\n")) {
    const at = line.match(/assert\.ts\((\d+),/);
    if (!at) continue;

    const declaration = source[Number(at[1]) - 1] ?? "";
    const pair = declaration.match(/Assert<Local\.(\w+), Gen\["(\w+)"\]>/);
    if (pair) seen.add(`  ${pair[2]} (backend) does not match ${pair[1]} (types.ts)`);
  }

  return [...seen];
}

try {
  execFileSync(
    path.join(ROOT, "node_modules", ".bin", "tsc"),
    ["--noEmit", "-p", "tsconfig.contract.json"],
    { cwd: ROOT, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] },
  );
} catch (error) {
  const failures = nameFailures(`${error.stdout ?? ""}${error.stderr ?? ""}`);
  fail(
    `types.ts and the backend schema disagree:\n${failures.join("\n")}\n\n` +
      "Read src/lib/contract/generated.ts for what the backend actually sends.",
  );
}

console.log(`contract: ${pairs} pairs match`);
